service: justwatch

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  environment:
    NOTIFICATION_EMAIL: ${env:NOTIFICATION_EMAIL}
    TOKEN_JUSTWATCH: ${env:TOKEN_JUSTWATCH}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: '*'

functions:
  newRelease:
    handler: src/handler.newRelease
    events:
      - schedule: rate(1 day)