version: 2

defaults: &defaults  
  docker:
    - image: circleci/node:8

jobs:
  build:
    <<: *defaults
    steps:
      - checkout      
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: 
          name: Install npm
          command: npm install
      - run:
          name: Test
          command: npm test
      - store_artifacts:
          path: .coverage
          prefix: .coverage
      - save_cache:          
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - .coverage  
  upload_report:
    <<: *defaults
    steps:      
      - checkout
      - attach_workspace:
          at: ~/tmp
      - run:
          name: Submit Coverage
          command: npm run coverage      


workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - upload_report:
          requires:
            - build
          filters:
            branches:
              only: master
      